name: Basic Setup
description: Install Bun and other dependencies
runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version-file: package.json
    - name: Install Dependencies
      shell: bash
      run: bun install --frozen-lockfile
