import { consola } from 'consola';
import {
  InlineConfig,
  resolveConfig,
  type AllChromeOptions,
  type CustomEnv,
} from '../config';
import { copyFile, writeFile, readFile } from 'node:fs/promises';
import { ChromeWebStoreV1_1Options } from '../stores/chrome-web-store-v1.1';
import { ChromeWebStoreV2Options } from '../stores/chrome-web-store-v2';
import { FirefoxAddonStoreV5Options } from '../stores/firefox-addon-store-v5';
import { EdgeAddonStoreV1_1Options } from '../stores/edge-addon-store-v1.1';
import { OperaAddonsStoreOptions } from '../stores/opera-addons-store';
import { ofetch } from 'ofetch';

type Entry = [key: keyof CustomEnv, value: string | number | boolean];

const envFile = '.env.submit';

export async function init(config: InlineConfig) {
  consola.info(`Initialize or update an existing \`${envFile}\` file.`);

  const previousConfig = resolveConfig(config);

  // Types are wrong? This actually returns a Promise<string[]>
  const stores = await prompt<string[]>(
    'What stores do you want to configure? \x1b[2m(use ↑/↓ and space to select)\x1b[0m',
    {
      type: 'multiselect',
      options: [
        { value: 'chrome', label: 'Chrome Web Store' },
        { value: 'firefox', label: 'Firefox Addon Store' },
        { value: 'edge', label: 'Edge Addon Store' },
        { value: 'opera', label: 'Opera Addons' },
      ],
      required: true,
    },
  );
  if (!stores?.length) {
    consola.warn('No stores selected, exiting without making any changes.');
    process.exit(1);
  }

  const replacements: Entry[] = [];
  if (stores?.includes('chrome')) {
    replacements.push(
      ...(await initChrome(previousConfig.chrome as AllChromeOptions)),
    );
  }
  if (stores?.includes('firefox')) {
    replacements.push(
      ...(await initFirefox(
        previousConfig.firefox as
          | Partial<FirefoxAddonStoreV5Options>
          | undefined,
      )),
    );
  }
  if (stores?.includes('edge')) {
    replacements.push(...(await initEdge(previousConfig.edge)));
  }
  if (stores?.includes('opera')) {
    replacements.push(...(await initOpera(previousConfig.opera)));
  }

  await updateEnvFile(replacements);
  console.log();
  consola.log(
    'To submit an update, run:\n\n  `publish-extension --chrome-zip path/to/extension.zip \\`\n    `--firefox-zip path/to/extension.zip \\`\n    `--edge-zip path/to/extension.zip \\`\n    `--opera-zip path/to/extension.zip`',
  );
}

async function prompt<T>(
  message: Parameters<typeof consola.prompt>[0],
  options: Parameters<typeof consola.prompt>[1],
  previousValue?: string,
): Promise<T> {
  let result = await consola.prompt(message, {
    default: previousValue,
    placeholder: previousValue,
    ...options,
  });
  // When canceling, a symbol is returned instead of the value.
  if (typeof result === 'symbol') {
    throw Error('Canceled');
  }
  if (typeof result === 'string') {
    result = result.trim();
  }
  return result as T;
}

async function initChrome(
  previousOptions: Partial<AllChromeOptions> | undefined,
): Promise<Entry[]> {
  const entries: Entry[] = [];

  console.log();
  consola.start('Chrome Web Store\n');

  const apiVersion = await prompt<string>(
    'Which Chrome Web Store API version do you want to use?',
    {
      type: 'select',
      options: [
        {
          label: 'v2 (recommended)',
          value: 'v2',
          hint: 'Uses a service account — required after October 15th, 2026',
        },
        {
          label: 'v1.1 (deprecated)',
          value: 'v1.1',
          hint: 'Will stop working October 15th, 2026',
        },
      ],
      initial: previousOptions?.apiVersion ?? 'v2',
    },
  );
  entries.push(['CHROME_API_VERSION', apiVersion]);

  consola.log('`--chrome-extension-id` can be found:');
  consola.log('  1. Under the extension name in the CWS developer console');
  consola.log('  2. In the URL of the CWS page for the item');
  consola.log('Example: `ocfdgncpifmegplaglcnglhioflaimkd`');
  const extensionId = await prompt<string>(
    'Enter the extension ID:',
    { type: 'text' },
    previousOptions?.extensionId,
  );
  entries.push(['CHROME_EXTENSION_ID', extensionId]);

  if (apiVersion === 'v2') {
    entries.push(
      ...(await initChromeV2(
        previousOptions as Partial<ChromeWebStoreV2Options>,
      )),
    );
  } else {
    entries.push(
      ...(await initChromeV1_1(
        previousOptions as Partial<ChromeWebStoreV1_1Options>,
      )),
    );
  }

  return entries;
}

async function initChromeV1_1(
  previousOptions: Partial<ChromeWebStoreV1_1Options> | undefined,
): Promise<Entry[]> {
  const entries: Entry[] = [];

  console.log();
  consola.log(
    '`--chrome-client-id` and `--chrome-client-secret` are generated by following the "Initial Setup" from:',
  );
  console.log('https://developer.chrome.com/docs/webstore/using-api#setup');
  const clientId = await prompt<string>(
    'Enter your client ID:',
    { type: 'text' },
    previousOptions?.clientId,
  );
  entries.push(['CHROME_CLIENT_ID', clientId]);
  const clientSecret = await prompt<string>(
    'Enter your client secret:',
    { type: 'text' },
    previousOptions?.clientSecret,
  );
  entries.push(['CHROME_CLIENT_SECRET', clientSecret]);

  const generateRefreshToken = await prompt<boolean>(
    'Generate new refresh token?',
    { type: 'confirm' },
  );
  if (generateRefreshToken) {
    const authCodeUrl = `https://accounts.google.com/o/oauth2/auth?response_type=code&scope=https://www.googleapis.com/auth/chromewebstore&client_id=${clientId}&redirect_uri=urn:ietf:wg:oauth:2.0:oob`;
    consola.log(authCodeUrl);
    const authCode = await consola.prompt(
      'Open the above URL, login, and enter the auth code:',
      {
        type: 'text',
        required: true,
      },
    );
    const data = new URLSearchParams();
    data.set('client_id', clientId);
    data.set('client_secret', clientSecret);
    data.set('code', authCode);
    data.set('grant_type', 'authorization_code');
    data.set('redirect_uri', 'urn:ietf:wg:oauth:2.0:oob');
    const tokenUrl = `https://accounts.google.com/o/oauth2/token`;
    const res = await ofetch<{ refresh_token: string }>(tokenUrl, {
      method: 'POST',
      body: data,
    });
    const refreshToken = res.refresh_token;
    consola.info(`Refresh token: \`${refreshToken}\``);
    entries.push(['CHROME_REFRESH_TOKEN', refreshToken]);
  }

  const publishTarget = await prompt<string>(
    '`--chrome-publish-target`: Where do you want to release to?',
    {
      type: 'select',
      options: [
        {
          label: 'Default',
          value: 'default',
          hint: 'Public release channel',
        },
        {
          label: 'Trusted Testers',
          value: 'trustedTesters',
          hint: 'Prerelease, internal channel',
        },
      ],
      initial: previousOptions?.publishTarget,
    },
    previousOptions?.publishTarget,
  );
  entries.push(['CHROME_PUBLISH_TARGET', publishTarget]);

  const submitForReview = await prompt<boolean>(
    'When uploading, automatically submit the new update for review?',
    { type: 'confirm' },
    String(!previousOptions?.skipSubmitReview),
  );
  entries.push(['CHROME_SKIP_SUBMIT_REVIEW', !submitForReview]);

  return entries;
}

async function initChromeV2(
  previousOptions: Partial<ChromeWebStoreV2Options> | undefined,
): Promise<Entry[]> {
  const entries: Entry[] = [];

  console.log();
  consola.log(
    '`--chrome-publisher-id` is the publisher ID found in the CWS developer dashboard URL:',
  );
  consola.log('  1. Visit https://chrome.google.com/webstore/devconsole');
  consola.log(
    '  2. In the top right corner, select the publisher your extension is published under (you may only have one)',
  );
  consola.log('  3. The publisher ID is the UUID in the URL');
  consola.log(
    'Example: `https://chrome.google.com/webstore/devconsole/27416ae5-5dfd-41ec-bb34-8a385fddab89 -> 27416ae5-5dfd-41ec-bb34-8a385fddab89`',
  );
  const publisherId = await prompt<string>(
    'Enter your publisher ID:',
    { type: 'text' },
    previousOptions?.publisherId,
  );
  entries.push(['CHROME_PUBLISHER_ID', publisherId]);

  console.log();
  consola.log(
    'A Google Cloud service account with a JSON key is required for the v2 API.',
  );
  consola.log(
    "  1. Follow Google's official guide to create a service account: https://developer.chrome.com/docs/webstore/service-accounts",
  );
  consola.log(
    '  2. When you get to "Obtain access tokens", follow "Use a JSON Web Token" and stop after downloading the JSON file',
  );
  consola.log(
    '    > WARNING: Google no longer recommends creating service worker keys, but this is the only form of auth accepted by publish-extension for now.',
  );
  consola.log(
    '  3. Open the JSON file and use the `client_email` and `private_key` fields below.',
  );
  const serviceAccountClientEmail = await prompt<string>(
    "Enter the service account's client email:",
    { type: 'text' },
    previousOptions?.serviceAccountClientEmail,
  );
  entries.push([
    'CHROME_SERVICE_ACCOUNT_CLIENT_EMAIL',
    serviceAccountClientEmail,
  ]);

  const serviceAccountPrivateKey = await prompt<string>(
    "Enter the service account's private key (keep the \\n in the string when copying it here):",
    { type: 'text' },
    previousOptions?.serviceAccountPrivateKey,
  );
  entries.push([
    'CHROME_SERVICE_ACCOUNT_PRIVATE_KEY',
    serviceAccountPrivateKey,
  ]);

  const submitForReview = await prompt<boolean>(
    'When uploading, automatically submit the new update for review?',
    { type: 'confirm' },
    String(!previousOptions?.skipSubmitReview),
  );
  entries.push(['CHROME_SKIP_SUBMIT_REVIEW', !submitForReview]);

  if (submitForReview) {
    const skipReview = await prompt<boolean>(
      '`--chrome-skip-review`: Skip the review process and publish immediately? (Only valid for eligible updates like ad-blocker rule changes)',
      { type: 'confirm' },
      String(previousOptions?.skipReview ?? false),
    );
    entries.push(['CHROME_SKIP_REVIEW', skipReview]);

    const publishType = await prompt<string>(
      '`--chrome-publish-type`: When should the extension be published after review?',
      {
        type: 'select',
        options: [
          {
            label: 'Default',
            value: 'DEFAULT_PUBLISH',
            hint: 'Publish immediately after approval',
          },
          {
            label: 'Staged',
            value: 'STAGED_PUBLISH',
            hint: 'Stage for publishing later',
          },
        ],
        initial: previousOptions?.publishType ?? 'DEFAULT_PUBLISH',
      },
    );
    if (publishType !== 'DEFAULT_PUBLISH') {
      entries.push(['CHROME_PUBLISH_TYPE', publishType]);
    }

    const setDeployPercentage = await prompt<boolean>(
      'Set an initial deploy percentage for the rollout?',
      { type: 'confirm' },
    );
    if (setDeployPercentage) {
      let deployPercentage: number | undefined;
      while (true) {
        const input = await prompt<string>(
          '`--chrome-deploy-percentage`: Enter a deploy percentage (1-100):',
          { type: 'text' },
          previousOptions?.deployPercentage
            ? String(previousOptions.deployPercentage)
            : undefined,
        );
        const parsed = Number(input.trim());
        if (Number.isInteger(parsed) && parsed >= 1 && parsed <= 100) {
          deployPercentage = parsed;
          break;
        }
        consola.warn('Please enter a valid integer between 1 and 100.');
      }
      entries.push(['CHROME_DEPLOY_PERCENTAGE', deployPercentage!]);
    }
  }

  return entries;
}

async function initFirefox(
  previousOptions: Partial<FirefoxAddonStoreV5Options> | undefined,
): Promise<Entry[]> {
  const entries: Entry[] = [];

  console.log();
  consola.start('Firefox Addon Store\n');

  consola.info(
    'Your `--firefox-extension-id` is listed at the bottom of the details page on:',
  );
  console.log('https://addons.mozilla.org/en-US/developers/');
  const extensionId = await prompt<string>(
    'Enter extension ID:',
    {
      type: 'text',
    },
    previousOptions?.extensionId,
  );
  entries.push(['FIREFOX_EXTENSION_ID', extensionId]);

  console.log();
  consola.log(
    '`--firefox-jwt-issuer` and `--firefox-jwt-secret` are available at:',
  );
  console.log('https://addons.mozilla.org/developers/addon/api/key/');
  const jwtIssuer = await prompt<string>(
    'Enter your JWT issuer:',
    { type: 'text' },
    previousOptions?.jwtIssuer,
  );
  entries.push(['FIREFOX_JWT_ISSUER', jwtIssuer]);
  const jwtSecret = await prompt<string>(
    'Enter your JWT secret:',
    { type: 'text' },
    previousOptions?.jwtSecret,
  );
  entries.push(['FIREFOX_JWT_SECRET', jwtSecret]);

  const channel = await prompt<string>(
    '`--firefox-channel`: Which channel do you want to release to?',
    {
      type: 'select',
      options: [
        {
          label: 'Listed',
          value: 'listed',
          hint: 'Hosted on addons.mozilla.com',
        },
        { label: 'Unlisted', value: 'unlisted', hint: 'For self-hosting' },
      ],
      initial: previousOptions?.channel,
    },
    previousOptions?.channel,
  );
  entries.push(['FIREFOX_CHANNEL', channel]);

  return entries;
}

async function initOpera(
  previousOptions: Partial<OperaAddonsStoreOptions> | undefined,
): Promise<Entry[]> {
  const entries: Entry[] = [];

  console.log();
  consola.start('Opera Addons\n');

  consola.info(
    'Your `--opera-package-id` is listed in the URL of your addon developer dashboard, example:\n' +
      'https://addons.opera.com/developer/package/<packageId>',
  );

  let packageId: number | undefined;
  while (true) {
    const input = await prompt<string>(
      'Enter the package ID (packageId):',
      { type: 'text' },
      previousOptions?.packageId
        ? String(previousOptions.packageId)
        : undefined,
    );

    const parsed = Number(input.trim());
    if (Number.isInteger(parsed) && parsed > 0) {
      packageId = parsed;
      break;
    }

    consola.warn('Please enter a valid positive integer for the package ID.');
  }
  entries.push(['OPERA_PACKAGE_ID', packageId]);

  consola.info(
    'Your `--opera-session-id` is the `sessionid` cookie available on the Opera Addons website: ' +
      'https://addons.opera.com/developer/',
  );
  const sessionId = await prompt<string>(
    'Enter the session ID (sessionid):',
    { type: 'text' },
    previousOptions?.sessionId,
  );
  entries.push(['OPERA_SESSION_ID', sessionId]);

  const submitForReview = await prompt<boolean>(
    'When uploading, automatically submit new update for review?',
    { type: 'confirm' },
    String(!previousOptions?.skipSubmitReview),
  );
  entries.push(['OPERA_SKIP_SUBMIT_REVIEW', !submitForReview]);

  return entries;
}

async function initEdge(
  previousOptions: Partial<EdgeAddonStoreV1_1Options> | undefined,
): Promise<Entry[]> {
  const entries: Entry[] = [];

  console.log();
  consola.start('Edge Addon Store\n');

  consola.info(
    'Your `--edge-product-id` is listed On the developer dashboard, at the top of the page under the extension name',
  );
  console.log('https://partner.microsoft.com/dashboard/microsoftedge/overview');
  const productId = await prompt<string>(
    'Enter product ID:',
    {
      type: 'text',
    },
    previousOptions?.productId,
  );
  entries.push(['EDGE_PRODUCT_ID', productId]);

  console.log();
  consola.log(
    '`--edge-client-id` and either `--edge-api-key` (API v1.1) or `--edge-client-secret` and `--edge-access-token-url` (API v1.0) can be created following:',
  );
  console.log(
    'https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api#before-you-begin',
  );
  const clientId = await prompt<string>(
    'Enter your client ID:',
    { type: 'text' },
    previousOptions?.clientId,
  );
  entries.push(['EDGE_CLIENT_ID', clientId]);

  const apiKey = await prompt<string>(
    'Enter your API key:',
    { type: 'text' },
    previousOptions?.apiKey,
  );
  entries.push(['EDGE_API_KEY', apiKey]);

  const submitForReview = await prompt<boolean>(
    'When uploading, automatically submit new update for review?',
    { type: 'confirm' },
    String(!previousOptions?.skipSubmitReview),
  );
  entries.push(['EDGE_SKIP_SUBMIT_REVIEW', !submitForReview]);

  return entries;
}

async function updateEnvFile(entries: Entry[]) {
  consola.start(`Writing to \`${envFile}\`...`);
  let template = await readFile(envFile, 'utf-8').catch(() => '');

  for (const [name, value] of entries) {
    const formattedValue = typeof value === 'string' ? `"${value}"` : value;
    const replacement = `${name}=${formattedValue}`;
    const pattern = new RegExp(`^${name}=.*$`, 'm');
    const existing = template.match(pattern);
    if (existing) {
      template = template.replace(existing[0], replacement);
    } else {
      template += `\n${replacement}`;
    }
  }

  const backupFilename = `${envFile}.backup-${Date.now()}`;
  await copyFile(envFile, backupFilename)
    .then(() => {
      consola.info(`Backed up old \`${envFile}\` to \`${backupFilename}\``);
    })
    .catch(() => {
      // If the file doesn't exist, continue
    });

  await writeFile(envFile, template, 'utf-8');

  console.log();
  consola.success('Wrote config to `.env.submit`');
}
